on: [push, pull_request]
name: Test
jobs:
  test:
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ./src/github.com/${{ github.repository }}

    - name: Get dependencies
      run: go get -v -u ./...

    - name: Run unit tests
      run: go test -cover ./...

    - name: Install Terraform
      uses: little-core-labs/install-terraform@v1

    - name : Terraform Apply
      run: |
        terraform init ./src/github.com/${{ github.repository }}/_build/deploy
        terraform plan -var="credentials_file=${{ secrets.gcp_service_account }} ./src/github.com/${{ github.repository }}/_build/deploy"
        terraform apply -var="credentials_file=${{ secrets.gcp_service_account }}" -auto-approve ./src/github.com/${{ github.repository }}/_build/deploy